# Linear x up / down L3
axis_linear: 1 # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

# Angular z left / right R3
axis_angular: 2 # Right thumb stick horizontal
scale_angular: 0.7

enable_button: 5 # R1 button
enable_turbo_button: 4 # L1 button
