# Linear x up / down L3
axis_linear: 1 # Left thumb stick vertical
scale_linear: 0.10
scale_linear_turbo: 0.15

# Angular z left / right R3
axis_angular: 3 # Right thumb stick horizontal
scale_angular: 0.6

enable_button: 5 # R1 button
enable_turbo_button: 4 # L1 button
